FORMAT: 1A
HOST: http://departments.apiblueprint.org/

# Department Codes

Find and access featured data or web services from the Department's agencies and mission areas. This page will be updated as agencies make available new developer tools and data resources, so be sure to check back often. Questions and feedback about this page can be directed to webmaster@foo.gov

Thank you for your interest in the agenices  APIs. From Version 2 on, all of our APIs require a basic API Key. We are only using the keys to improve our metrics, our customer service, and the security of your queries. We are not using them for rate limiting or monitoring, but please do review our Terms of Service. If you have any questions about our API Keys, please e-mail us at api@usa.gov.

## Department Collection [/departments]

### List All Department Codes [GET]

+ Response 200 (application/json)

        [
            {
                "DepartmentDesc": "Sewer",
                "id": 9002
            }, 
            {
                "DepartmentDesc": "Gas Department",
                "id": 10000
            }, 
            {
                "DepartmentDesc": "Parks and Recreation",
                "id": 512
            },
            {
                "DepartmentDesc": "Water",
                "id": 25
            }   
        ]
        
## Search Parameters for Business Service Providers [/providers]
Returns business service providers for a match in the company_name, company_description, or contact_name fields.

### Business Service Providers [GET]

Lists all buasiness providers to the department

+ Response 200 (application/json)

        [
            {
                "name": "Guinness",
                "description": "No preservatives or additives. 100% natural, ingredients create a unique flavour",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2680B911AEB03B8C3B6EF22F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Pilsner Urquell",
                "description": "World's first pilsner. Grainy malt center with a light touch of butter flavor",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D38CC50D762E50731F505711F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Schlappe-Seppel",
                "description": "Smooth bitter, tangy, fruity, full-bodied - more than a beer, it's an attitude",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DFE12285193404897A6331F4F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Heineken",
                "description": "Crisp, clean and refreshing, this popular beer is a classic European style Lager",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DE79A523EC91B0687D5AA852F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Löwenbräu",
                "description": "This all natural beer is fully balanced with dry but crisp, bitter undertones",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DA09DF49105AB60AFEBAC1E0F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            }
        ]