FORMAT: 1A
HOST: http://departments.apiblueprint.org/

# Department Codes

This API is for providing Department Codes to be used in a web application or chatbot.


## Department Collection [/departments]

### List All Department Codes [GET]

+ Response 200 (application/json)

        [
            {
                "DepartmentDesc": "Sewer",
                "id": 9002
            }, 
            {
                "DepartmentDesc": "Gas Department",
                "id": 10000
            }, 
            {
                "DepartmentDesc": "Parks and Recreation",
                "id": 512
            },
            {
                "DepartmentDesc": "Water",
                "id": 25
            }   
        ]